/*
 * (C) 2003-2006 Gabest
 * (C) 2006-2013 see Authors.txt
 *
 * This file is part of MPC-HC.
 *
 * MPC-HC is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * MPC-HC is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

// For configuring which internal filters are included into the build.

#pragma once

// By default all internal filters are enabled except for lite builds
// where they are all disabled.
#if defined(MPCHC_LITE)
#define INTERNAL_FILTERS_ENABLED 0
#else
#define INTERNAL_FILTERS_ENABLED 1
#endif

#define CCCP_FILTER_ENABLED  1
#define CCCP_FILTER_DISABLED 0

// Internal source filters
#define INTERNAL_SOURCEFILTER_AVI       CCCP_FILTER_ENABLED
#define INTERNAL_SOURCEFILTER_CDDA      CCCP_FILTER_DISABLED
#define INTERNAL_SOURCEFILTER_CDXA      CCCP_FILTER_DISABLED
#define INTERNAL_SOURCEFILTER_DSM       CCCP_FILTER_ENABLED
#define INTERNAL_SOURCEFILTER_DTSAC3    CCCP_FILTER_ENABLED
#define INTERNAL_SOURCEFILTER_VTS       CCCP_FILTER_DISABLED
#define INTERNAL_SOURCEFILTER_DVSOURCE  CCCP_FILTER_DISABLED
#define INTERNAL_SOURCEFILTER_FLIC      CCCP_FILTER_DISABLED
#define INTERNAL_SOURCEFILTER_FLAC      CCCP_FILTER_ENABLED
#define INTERNAL_SOURCEFILTER_FLV       CCCP_FILTER_DISABLED
#define INTERNAL_SOURCEFILTER_MATROSKA  CCCP_FILTER_DISABLED
#define INTERNAL_SOURCEFILTER_MP4       CCCP_FILTER_DISABLED
#define INTERNAL_SOURCEFILTER_OGG       CCCP_FILTER_DISABLED
#define INTERNAL_SOURCEFILTER_MPEGAUDIO CCCP_FILTER_ENABLED
#define INTERNAL_SOURCEFILTER_MPEG      CCCP_FILTER_DISABLED
#define INTERNAL_SOURCEFILTER_REALMEDIA CCCP_FILTER_DISABLED
#define INTERNAL_SOURCEFILTER_SHOUTCAST CCCP_FILTER_ENABLED
#define INTERNAL_SOURCEFILTER_UDP       CCCP_FILTER_ENABLED
#define INTERNAL_SOURCEFILTER_AVI2AC3   CCCP_FILTER_DISABLED
#define INTERNAL_SOURCEFILTER_RFS       CCCP_FILTER_ENABLED

// Internal audio decoders
#define INTERNAL_DECODER_LPCM           CCCP_FILTER_DISABLED
#define INTERNAL_DECODER_PS2AUDIO       CCCP_FILTER_DISABLED
#define INTERNAL_DECODER_REALAUDIO      CCCP_FILTER_DISABLED
#define INTERNAL_DECODER_PCM            CCCP_FILTER_DISABLED

// Internal audio decoders (FFmpeg)
#define INTERNAL_DECODER_AC3            CCCP_FILTER_DISABLED /* also E-AC3, TrueHD, MLP */
#define INTERNAL_DECODER_DTS            CCCP_FILTER_DISABLED
#define INTERNAL_DECODER_AAC            CCCP_FILTER_DISABLED
#define INTERNAL_DECODER_ALAC           CCCP_FILTER_DISABLED
#define INTERNAL_DECODER_ALS            CCCP_FILTER_DISABLED
#define INTERNAL_DECODER_MPEGAUDIO      CCCP_FILTER_DISABLED
#define INTERNAL_DECODER_VORBIS         CCCP_FILTER_DISABLED
#define INTERNAL_DECODER_NELLYMOSER     CCCP_FILTER_DISABLED
#define INTERNAL_DECODER_AMR            CCCP_FILTER_DISABLED
#define INTERNAL_DECODER_ADPCM          CCCP_FILTER_DISABLED
#define INTERNAL_DECODER_FLAC           CCCP_FILTER_DISABLED

// Internal video decoders
#define INTERNAL_DECODER_MPEG1          CCCP_FILTER_DISABLED
#define INTERNAL_DECODER_MPEG2          CCCP_FILTER_DISABLED
#define INTERNAL_DECODER_REALVIDEO      CCCP_FILTER_DISABLED

// Internal video decoders (FFmpeg)
#define INTERNAL_DECODER_H264           CCCP_FILTER_DISABLED
#define INTERNAL_DECODER_VC1            CCCP_FILTER_DISABLED
#define INTERNAL_DECODER_FLV            CCCP_FILTER_DISABLED
#define INTERNAL_DECODER_VP356          CCCP_FILTER_DISABLED
#define INTERNAL_DECODER_DIVX           CCCP_FILTER_DISABLED
#define INTERNAL_DECODER_XVID           CCCP_FILTER_DISABLED
#define INTERNAL_DECODER_WMV            CCCP_FILTER_DISABLED
#define INTERNAL_DECODER_MSMPEG4        CCCP_FILTER_DISABLED
#define INTERNAL_DECODER_SVQ            CCCP_FILTER_DISABLED
#define INTERNAL_DECODER_H263           CCCP_FILTER_DISABLED
#define INTERNAL_DECODER_THEORA         CCCP_FILTER_DISABLED
#define INTERNAL_DECODER_AMVV           CCCP_FILTER_DISABLED
#define INTERNAL_DECODER_VP8            CCCP_FILTER_DISABLED
#define INTERNAL_DECODER_MJPEG          CCCP_FILTER_DISABLED
#define INTERNAL_DECODER_INDEO          CCCP_FILTER_DISABLED

// DXVA decoders
#define INTERNAL_DECODER_H264_DXVA      CCCP_FILTER_DISABLED
#define INTERNAL_DECODER_VC1_DXVA       CCCP_FILTER_DISABLED
#define INTERNAL_DECODER_MPEG2_DXVA     CCCP_FILTER_DISABLED
#define INTERNAL_DECODER_WMV3_DXVA      CCCP_FILTER_DISABLED


// Groups
#define HAS_SOURCEFILTERS \
    (INTERNAL_SOURCEFILTER_AVI || INTERNAL_SOURCEFILTER_CDDA || INTERNAL_SOURCEFILTER_CDXA || INTERNAL_SOURCEFILTER_DSM || INTERNAL_SOURCEFILTER_DTSAC3 ||       \
    INTERNAL_SOURCEFILTER_VTS || INTERNAL_SOURCEFILTER_DVSOURCE || INTERNAL_SOURCEFILTER_FLIC || INTERNAL_SOURCEFILTER_FLAC || INTERNAL_SOURCEFILTER_FLV ||      \
    INTERNAL_SOURCEFILTER_MATROSKA || INTERNAL_SOURCEFILTER_MP4 || INTERNAL_SOURCEFILTER_OGG || INTERNAL_SOURCEFILTER_MPEGAUDIO || INTERNAL_SOURCEFILTER_MPEG || \
    INTERNAL_SOURCEFILTER_REALMEDIA || INTERNAL_SOURCEFILTER_SHOUTCAST || INTERNAL_SOURCEFILTER_UDP || INTERNAL_SOURCEFILTER_AVI2AC3 || INTERNAL_SOURCEFILTER_RFS)

#define HAS_OTHER_AUDIO_DECODERS \
    (INTERNAL_DECODER_LPCM || INTERNAL_DECODER_PS2AUDIO || INTERNAL_DECODER_REALAUDIO || INTERNAL_DECODER_PCM)

#define HAS_OTHER_VIDEO_DECODERS \
    (INTERNAL_DECODER_MPEG1 || INTERNAL_DECODER_MPEG2 || INTERNAL_DECODER_REALVIDEO)

#define HAS_OTHER_DECODERS \
    (HAS_OTHER_AUDIO_DECODERS || HAS_OTHER_VIDEO_DECODERS)

#define HAS_FFMPEG_AUDIO_DECODERS \
    (INTERNAL_DECODER_AC3 || INTERNAL_DECODER_AAC || INTERNAL_DECODER_ALAC || INTERNAL_DECODER_ALS || INTERNAL_DECODER_DTS || INTERNAL_DECODER_MPEGAUDIO || \
    INTERNAL_DECODER_VORBIS || INTERNAL_DECODER_NELLYMOSER || INTERNAL_DECODER_AMR || INTERNAL_DECODER_ADPCM || INTERNAL_DECODER_REALAUDIO || INTERNAL_DECODER_FLAC)

#define HAS_FFMPEG_VIDEO_DECODERS \
    (INTERNAL_DECODER_H264 || INTERNAL_DECODER_VC1 || INTERNAL_DECODER_FLV || INTERNAL_DECODER_VP356 || INTERNAL_DECODER_DIVX || INTERNAL_DECODER_XVID ||    \
    INTERNAL_DECODER_WMV || INTERNAL_DECODER_MSMPEG4 || INTERNAL_DECODER_SVQ || INTERNAL_DECODER_H263 || INTERNAL_DECODER_THEORA || INTERNAL_DECODER_AMVV || \
    INTERNAL_DECODER_VP8 || INTERNAL_DECODER_MJPEG || INTERNAL_DECODER_INDEO || INTERNAL_DECODER_REALVIDEO)

#define HAS_FFMPEG_DECODERS \
    (HAS_FFMPEG_AUDIO_DECODERS || HAS_FFMPEG_VIDEO_DECODERS)

#define HAS_DXVA_VIDEO_DECODERS \
    (INTERNAL_DECODER_H264_DXVA || INTERNAL_DECODER_VC1_DXVA || INTERNAL_DECODER_MPEG2_DXVA || INTERNAL_DECODER_WMV3_DXVA)

#define HAS_FFMPEG \
    (HAS_FFMPEG_AUDIO_DECODERS || HAS_FFMPEG_VIDEO_DECODERS || HAS_DXVA_VIDEO_DECODERS)
